#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

dir=$(pwd)
cd $dir

PREV_VERSION=$(sed -n 1p VERSION)
OP=$(sed -n 2p VERSION)

nextversion=$(bash semver.sh -${OP} ${PREV_VERSION})

echo $nextversion

echo ${nextversion} > VERSION
echo 'p' >> VERSION

git add VERSION
git tag ${nextversion}