version: '3.8'

services:
    myapp:
        build: .
        sysctls:
            - net.ipv4.ip_unprivileged_port_start=0
        container_name: asaasphp
        environment:
            - DOCKER=1
            - DEV_MODE=1
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_NAME=outputenglish
            - DB_NAME_LOG=outputenglish
            - DB_USER=outputenglish
            - DB_PASS=outputenglish
            - DB_DATABASE=outputenglish
            - DB_USERNAME=daniel
            - DB_PASSWORD=daniel
            - BK_SYNC=1
            - XDEBUG_ENABLED=true
            - XDEBUG_CONFIG=idekey=VSCODE
            - NODE_OPTIONS=--openssl-legacy-provider
        volumes:
            - .:/var/www/html
        ports:
            - 8888:80
